name: Deploy to demo site

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: build site
        run: |
          npm install
          npm run build:demo
        env:
          BROADCASTER_URL: 'https://uviboo.org/jam'
          ICE_SERVERS: 'url: stun:stun.l.google.com:19302'
